/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
@org.apache.avro.specific.AvroGenerated
public enum sex implements org.apache.avro.generic.GenericEnumSymbol<sex> {
  MALE, FEMALE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"sex\",\"symbols\":[\"MALE\",\"FEMALE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
